name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: Finsenty54/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c05e10597e2ebe37ea36cc17f8a97362
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
